name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:


    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - lint
          - typecheck

    steps:
      - uses: actions/checkout@v2
      - name: tox ${{ matrix.linter }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.linter }}
        with:
          args: tox

  tests:
    needs: lint
    runs-on: ubuntu-latest

    services:
      s3:
        image: docker://fingershock/fakes3
        ports:
          - 8000:8000

    strategy:
      fail-fast: false

      matrix:
        toxenv:
          - py36
          - py37
          - py38
          - py39

    steps:
      - uses: actions/checkout@v2

      - name: tox ${{ matrix.toxenv }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.toxenv }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          S3_URL: http://user:hackme@s3:8000/
        with:
          args: tox
